version: "3.9"

services:
  backend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_PATH: /data/todos.db
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - sqlite_data:/data
    ports:
      - "3001:3001"

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules:
  sqlite_data:
