# fly.toml app configuration file generated for fullstack-todo on 2025-10-17T18:55:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-todo'
primary_region = 'ams'

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"
  DATABASE_PATH = "/data/todos.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Persistent volume for SQLite database
[[mounts]]
  source = "sqlite_data"
  destination = "/data"
