# Fly.io Full-Stack Todo App Configuration
app = "fullstack-todo-whoisyurii"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"
  DATABASE_PATH = "/data/todos.db"
  FRONTEND_PATH = "/app/frontend"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

# Persistent volume for SQLite database
[[mounts]]
  source = "sqlite_data"
  destination = "/data"
